### ISSUE TITLE
proxysql-logrotate configuration leaves deleted files open

### ISSUE THREAD

**Issue by RasmusEdgar** [percona/proxysql-packaging#14]
Hi,

Thank you packaging proxysql for perconas repositories. 

There seems to be a problem with the included proxysql-logrotate configuration (where is it btw, can't find it in this repo), when rotating and deleting files the files are still attached to the proxysql process and therefore not deleted.

Check with:

sudo lsof +L1 | grep prox

Adding copytruncate to the proxysql-logrotate configuration seems to solve the problem.

Br,
Rasmus

**Comment by EvgeniyPatlan** [comment]
@RasmusEdgar this should be fixed in the upcoming release
