### ISSUE TITLE
deb package ignores /usr/sbin/policy-rc.d

### ISSUE THREAD

**Issue by rmarchei** [percona/proxysql-packaging#18]
On Ubuntu Xenial, proxysql daemon is always started during installation, even if `/usr/sbin/policy-rc.d` is configured not to automatically start services.

The problem seems to be in https://github.com/percona/proxysql-packaging/blob/master/debian/postinst#L55-L66, where systemctl/service are directly used instead of [invoke-rc.d](https://people.debian.org/~hmh/invokerc.d-policyrc.d-specification.txt)

**Comment by EvgeniyPatlan** [comment]
thanks for your report @rmarchei!
The issue should be fixed in the upcomming release
