### ISSUE TITLE
Service not starting automatically after a reboot on Debian Jessie

### ISSUE THREAD

**Issue by ryno83** [percona/proxysql-packaging#7]
Hi,
after upgrading from 1.3.6-1.1 to 1.3.7-1.1 on Debian Jessie, proxysql doesn't start automatically after a reboot. Then, if I start it manually with `service proxysql start`, everything goes well. I think the proxysql.service file is missing something. Maybe an [install] section.

I reinstalled 1.3.6 and everything is working fine.

**Comment by mindfl** [comment]
Hi! Same problem on Ubuntu 16.04 with proxysql 1.3.9-1.1.xenial from [percona repo](https://www.percona.com/doc/percona-server/LATEST/installation/apt_repo.html)

I fixed it like this:

1.  `systemctl edit proxysql`
2. Insert this:
```
[Unit]
After=network.target
```
3. Done

it would be great if proxysql would be started by default (i.e. without such changes).

**Comment by EvgeniyPatlan** [comment]
@mindfl could you please check with the latest version as it is strange
After=network.target exists in unitfile from 2017-07-03

**Comment by ryno83** [comment]
I'm using proxysql 1.4.3-1.1 on debian stretch and proxysql is not starting automatically after a reboot. `systemctl list-unit-files | grep proxysql` give me a **static** state.

**Comment by EvgeniyPatlan** [comment]
@ryno83 thanks for the info. I will check

**Comment by EvgeniyPatlan** [comment]
@ryno83 thanks for your report. I have fixed the issue and it should be available in next release
